"""Report generation for presentation analysis results."""
import json
from typing import Dict, List
from jinja2 import Template
from datetime import datetime
import logging

logger = logging.getLogger(__name__)


class ReportGenerator:
    """Generate reports in multiple formats from analysis data."""

    def __init__(self):
        """Initialize report generator."""
        self.timestamp = datetime.now().isoformat()

    def generate_html_report(self, analysis_data: Dict) -> str:
        """Generate HTML report.
        
        Args:
            analysis_data: Complete analysis dictionary
            
        Returns:
            HTML report as string
        """
        template_str = """
        <!DOCTYPE html>
        <html>
        <head>
            <title>PowerPoint Analysis Report</title>
            <style>
                body { font-family: Arial; margin: 20px; background: #f5f5f5; }
                .header { background: #2c3e50; color: white; padding: 20px; border-radius: 5px; }
                .slide { background: white; margin: 15px 0; padding: 15px; border-left: 4px solid #3498db; }
                .score { display: inline-block; background: #3498db; color: white; padding: 5px 10px; border-radius: 3px; }
                .recommendation { background: #ecf0f1; padding: 10px; margin: 10px 0; border-radius: 3px; }
                h1 { color: #2c3e50; }
                h2 { color: #34495e; }
                .overall-score { font-size: 24px; font-weight: bold; color: #27ae60; }
            </style>
        </head>
        <body>
            <div class="header">
                <h1>PowerPoint Presentation Analysis Report</h1>
                <p>Generated: {{ timestamp }}</p>
            </div>
            
            <h2>Presentation Overview</h2>
            <p><strong>Title:</strong> {{ metadata.title }}</p>
            <p><strong>Author:</strong> {{ metadata.author }}</p>
            <p><strong>Total Slides:</strong> {{ metadata.total_slides }}</p>
            
            <h2>Slide Analysis</h2>
            {% for slide in slides %}
            <div class="slide">
                <h3>Slide {{ slide.slide_number }}: {{ slide.title }}</h3>
                <p><strong>Word Count:</strong> {{ slide.word_count }}</p>
                <p><strong>Images:</strong> {{ slide.images_count }}</p>
                <p><strong>Density Rating:</strong> <span class="score">{{ slide.density_analysis.density_rating }}</span></p>
                <div class="recommendation">
                    <strong>Recommendation:</strong> {{ slide.density_analysis.recommendation }}
                </div>
            </div>
            {% endfor %}
            
            <footer style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #bdc3c7;">
                <p style="color: #7f8c8d;">Generated by PPT Reviewer Agent</p>
            </footer>
        </body>
        </html>
        """
        
        try:
            template = Template(template_str)
            metadata = analysis_data.get("metadata", {})
            slides = analysis_data.get("slides", [])
            
            html = template.render(
                timestamp=self.timestamp,
                metadata=metadata,
                slides=slides
            )
            
            logger.info("HTML report generated successfully")
            return html
        except Exception as e:
            logger.error(f"Error generating HTML report: {str(e)}")
            return f"<h1>Error generating report</h1><p>{str(e)}</p>"

    def generate_json_report(self, analysis_data: Dict) -> str:
        """Generate JSON report.
        
        Args:
            analysis_data: Complete analysis dictionary
            
        Returns:
            JSON report as string
        """
        try:
            report = {
                "timestamp": self.timestamp,
                "analysis": analysis_data,
                "report_version": "1.0",
            }
            
            logger.info("JSON report generated successfully")
            return json.dumps(report, indent=2)
        except Exception as e:
            logger.error(f"Error generating JSON report: {str(e)}")
            return json.dumps({"error": str(e)})

    def generate_markdown_report(self, analysis_data: Dict) -> str:
        """Generate Markdown report.
        
        Args:
            analysis_data: Complete analysis dictionary
            
        Returns:
            Markdown report as string
        """
        try:
            md = f"""# PowerPoint Analysis Report

**Generated:** {self.timestamp}

## Presentation Overview

- **Title:** {analysis_data.get('metadata', {}).get('title', 'Unknown')}
- **Author:** {analysis_data.get('metadata', {}).get('author', 'Unknown')}
- **Total Slides:** {analysis_data.get('metadata', {}).get('total_slides', 0)}

## Slide Analysis

"""
            
            for slide in analysis_data.get("slides", []):
                md += f"""### Slide {slide.get('slide_number')}: {slide.get('title', 'Untitled')}

- **Word Count:** {slide.get('word_count', 0)}
- **Images:** {slide.get('images_count', 0)}
- **Density:** {slide.get('density_analysis', {}).get('density_rating', 'N/A')}
- **Recommendation:** {slide.get('density_analysis', {}).get('recommendation', 'N/A')}

"""
            
            logger.info("Markdown report generated successfully")
            return md
        except Exception as e:
            logger.error(f"Error generating Markdown report: {str(e)}")
            return f"# Error\n\n{str(e)}"

    def generate_all_reports(self, analysis_data: Dict) -> Dict[str, str]:
        """Generate all report formats.
        
        Args:
            analysis_data: Complete analysis dictionary
            
        Returns:
            Dictionary with all report formats
        """
        return {
            "html": self.generate_html_report(analysis_data),
            "json": self.generate_json_report(analysis_data),
            "markdown": self.generate_markdown_report(analysis_data),
        }
